#include<iostream.h>
#include<conio.h>
#include<stdio.h>
#include<string.h>

void main()
{
	clrscr();
	for(int i=1;i<=35;i++) cout<<char(219);
	cout<<"> README <";
	for(int j=1;j<=35;j++) cout<<char(219);
	cout<<endl;
	cout<<"                      CENTRAL BOARD OF SECONDARY EDUCATION\n                   ANNUAL COMPUTER SCIENCE PROJECT EVALUATION\n\t\t\t   STD. XII : SESSION 2019-20"<<endl<<endl;
	cout<<"This project has been developed by students of DAV MODEL SCHOOL, DURGAPUR:"<<endl;
	cout<<" "<<(char)5<<"  Abesh Roy     , XII A1 <GAME CODE; SOUND; GRAPHICS; DEBUGGING> \n "<<char(5)<<"  Jayanta Pandit, XII A1 <GAME CODE; GRAPHICS; DATABASE; DEBUGGING>\n "<<char(5)<<"  Sourish Mandal, XII A1 <GAME CODE; DEBUGGING; EDITING>"<<endl<<endl;
	cout<<"PROJECT : Single Player Text-based Adventure/Survival Game using Turbo C++"<<endl;
	cout<<"BYTENAME (what we like to call it) : ZOMBIE APOCALYSE SURVIVOR VER1.1"<<endl<<endl;
	cout<<"PROJECT DESCRIPTION :"<<endl<<endl;
	cout<<"VER1.0 ended up implementing one of the most challenging and complex ideas of using structure variables as real life objects in the game. This upgraded VER1.1 includes the requisite update to the use of OOP, audio cues and integrated graphics using EGAVGA.BGI module of the TURBOC LIBRARY.";
	cout<<" The new implementations include an excessively wide range of class concept derivatives viz. file handling to save player profiles, and arrays (implemented throughout), as well as use of GRAPHICS.h and DOS.h headers. <PRESS ENTER> and enjoy playing."<<endl;
	cout<<endl;
	for(i=1;i<=79;i++) cout<<char(219);
	//cout<<"> README <";
	//for(j=1;j<=36;j++) cout<<char(219);
	getch();
	//clrscr();
	//cout<<"readme INFORMATION PORTAL:"<<endl<<endl;
	//cout<<"PROGRAM DESCRIPTION :"<<endl<<endl;
	//getch();
}